# Configurations
title:            Publish Test Maven
longtitle:        Publish Test Maven
author:           Alexandre Carvalho
email:            adcarvalho@gmail.com
description: >
  Testing publish test site.

baseurl: '/publish-test-maven'

remote_theme: oak3dev/architect

exclude: 
  - docs/pages/templates