name: Deploy Javadoc, Test results and Jacoco Report to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
      - name: Export project version
        run: echo "PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Generate reports
        run: ./mvnw --no-transfer-progress --batch-mode site
      - name: Deploy maven reports to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: target/site
          target-folder: docs/${{ env.PROJECT_VERSION }}/site
      - name: Deploy maven reports to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: target/site
          target-folder: docs/latest/site